<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizQuestionOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quiz_question_options')->insertOrIgnore([
        	[
                'id'               => 1,   
                'quiz_question_id' => 1,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 2,   
                'quiz_question_id' => 1,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 3,   
                'quiz_question_id' => 1,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 4,   
                'quiz_question_id' => 1,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 5,   
                'quiz_question_id' => 1,
                'option'           => "option 5",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 6,   
                'quiz_question_id' => 2,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 7,   
                'quiz_question_id' => 2,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 8,   
                'quiz_question_id' => 2,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 9,   
                'quiz_question_id' => 2,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 10,   
                'quiz_question_id' => 3,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 11,   
                'quiz_question_id' => 3,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 12,   
                'quiz_question_id' => 3,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 13,   
                'quiz_question_id' => 3,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 14,   
                'quiz_question_id' => 4,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 15,   
                'quiz_question_id' => 4,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 16,   
                'quiz_question_id' => 4,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 17,   
                'quiz_question_id' => 4,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 18,   
                'quiz_question_id' => 5,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 19,   
                'quiz_question_id' => 5,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 20,   
                'quiz_question_id' => 5,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 21,   
                'quiz_question_id' => 5,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 22,   
                'quiz_question_id' => 6,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 23,   
                'quiz_question_id' => 6,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 24,   
                'quiz_question_id' => 6,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 25,   
                'quiz_question_id' => 6,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 26,   
                'quiz_question_id' => 7,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 27,   
                'quiz_question_id' => 7,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 28,   
                'quiz_question_id' => 7,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 29,   
                'quiz_question_id' => 7,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 30,   
                'quiz_question_id' => 8,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 31,   
                'quiz_question_id' => 8,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 32,   
                'quiz_question_id' => 8,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 33,   
                'quiz_question_id' => 8,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 34,   
                'quiz_question_id' => 9,
                'option'           => "option 1",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 35,   
                'quiz_question_id' => 9,
                'option'           => "option 2",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 36,   
                'quiz_question_id' => 9,
                'option'           => "option 3",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 37,   
                'quiz_question_id' => 9,
                'option'           => "option 4",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ]
        ]);

    }
}