<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecapQuestionOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recap_question_options')->insertOrIgnore([
        	[
                'id'               => 1,   
                'recap_question_id'=> 1,
                'option'           => "",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 2,   
                'recap_question_id'=> 2,
                'option'           => "",
                'type'             => "textarea",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 3,   
                'recap_question_id'=> 3,
                'option'           => "",
                'type'             => "date",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 4,   
                'recap_question_id'=> 4,
                'option'           => "option 1",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 5,   
                'recap_question_id'=> 4,
                'option'           => "option 2",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 6,   
                'recap_question_id'=> 4,
                'option'           => "option 3",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 7,   
                'recap_question_id'=> 4,
                'option'           => "option 4",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 8,   
                'recap_question_id'=> 5,
                'option'           => "checkbox 1",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 9,   
                'recap_question_id'=> 5,
                'option'           => "checkbox 2",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 10,   
                'recap_question_id'=> 5,
                'option'           => "checkbox 3",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 11,   
                'recap_question_id'=> 6,
                'option'           => "radio 1",
                'type'             => "radio",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 12,   
                'recap_question_id'=> 6,
                'option'           => "radio 2",
                'type'             => "radio",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 13,   
                'recap_question_id'=> 7,
                'option'           => "",
                'type'             => "image",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 14,   
                'recap_question_id'=> 8,
                'option'           => "",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 15,   
                'recap_question_id'=> 9,
                'option'           => "",
                'type'             => "textarea",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 16,   
                'recap_question_id'=> 10,
                'option'           => "radio 1",
                'type'             => "radio",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 17,   
                'recap_question_id'=> 10,
                'option'           => "radio 2",
                'type'             => "radio",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 18,   
                'recap_question_id'=> 11,
                'option'           => "option 1",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 19,   
                'recap_question_id'=> 11,
                'option'           => "option 2",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 20,   
                'recap_question_id'=> 11,
                'option'           => "option 3",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 21,   
                'recap_question_id'=> 11,
                'option'           => "option 4",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 22,   
                'recap_question_id'=> 12,
                'option'           => "box 1",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 23,   
                'recap_question_id'=> 12,
                'option'           => "box 2",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 24,   
                'recap_question_id'=> 12,
                'option'           => "box 3",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 25,   
                'recap_question_id'=> 13,
                'option'           => "option 1",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 26,   
                'recap_question_id'=> 13,
                'option'           => "option 2",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 27,   
                'recap_question_id'=> 13,
                'option'           => "option 3",
                'type'             => "select",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 28,   
                'recap_question_id'=> 14,
                'option'           => "box 1",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 29,   
                'recap_question_id'=> 14,
                'option'           => "box 2",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 30,   
                'recap_question_id'=> 14,
                'option'           => "box 3",
                'type'             => "checkbox",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'id'               => 31,   
                'recap_question_id'=> 15,
                'option'           => "",
                'type'             => "text",
                'status'           => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ]
        ]);

    }
}